default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres1
  password: 123456

development:
  <<: *default
  database: yuvasoft3_development

test:
  <<: *default
  database: yuvasoft3_test

production:
  <<: *default
  database: yuvasoft3_development
